 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/notebooks/00-preliminaries.ipynb#Matrix---Matrix-Products" data-toc-modified-id="Matrix---Matrix-Products-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Matrix - Matrix Products</a></span></li><li><span><a href="http://localhost:8888/notebooks/notebooks/00-preliminaries.ipynb#Eigenvalues-of-a-Matrix" data-toc-modified-id="Eigenvalues-of-a-Matrix-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Eigenvalues of a Matrix</a></span></li></ul></div>

In [1]:
import numpy as np

In [2]:
A = np.array([[0.90, 0.07, 0.02, 0.01],
                [0, 0.93, 0.05, 0.02],
                [0, 0, 0.85, 0.15], 
               [0, 0, 0, 1.00]]).T
A.shape

(4, 4)

In [3]:
B = np.array([[.85, .1, .05, 0.]]).T
B.shape

(4, 1)

In [4]:
A @ B

array([[ 0.765 ],
       [ 0.1525],
       [ 0.0645],
       [ 0.018 ]])

In [5]:
A

array([[ 0.9 ,  0.  ,  0.  ,  0.  ],
       [ 0.07,  0.93,  0.  ,  0.  ],
       [ 0.02,  0.05,  0.85,  0.  ],
       [ 0.01,  0.02,  0.15,  1.  ]])

# Matrix - Matrix Products

In [6]:
demand = np.array([[6, 5, 3, 1],
                  [3, 6, 2, 2],
                  [3, 4, 3, 1]])
prices = np.array([[1.50, 1.00],
                   [2.00, 2.50],
                  [5.00, 4.50],
                  [16.00, 17.00]])


In [7]:
demand @ prices

array([[ 50. ,  49. ],
       [ 58.5,  61. ],
       [ 43.5,  43.5]])

# Eigenvalues of a Matrix

In [8]:
import scipy.linalg as la 

A = np.array([[1., 1000], [0, 1]])
B = np.array([[1, 1000], [0.001, 1]])

print(A)

print(B)

[[    1.  1000.]
 [    0.     1.]]
[[  1.00000000e+00   1.00000000e+03]
 [  1.00000000e-03   1.00000000e+00]]


In [9]:
np.set_printoptions(suppress=True, precision=4)

In [10]:
wA, vrA = la.eig(A)
wB, vrB = la.eig(B)

wA, wB


(array([ 1.+0.j,  1.+0.j]), array([ 2.+0.j,  0.+0.j]))