# Fundamentals of Numerical Linear Algebra

> The field of numerical linear algebra is more beautiful, and more fundamental, than its rather dull name may suggest. More beautiful, because it is full of powerful ideas that are **quite unlike those normally emphasized in a linear algebra course in a mathematics department**.[1]

- **Numerical linear algebra** is really *applied* linear algebra. It is here that one finds the essential ideas that every mathematical scientist needs to work effectively with vectors and matrices. 

- **Numerical linear algebra** is really functional analysis, but with emphasis always on **practical algorithmic ideas** rather than mathematical technicalities.

If any other mathematical topic is as fundamental to the mathematical sciences as **calculus** and **differential equations**, it is **numerical linear algebra**.

## Matrix-Vector Multiplication

To define multiplication between a [matrix](https://en.wikipedia.org/wiki/Matrix_(mathematics) $\matrix{A}$ and a [vector](https://en.wikipedia.org/wiki/Vector_algebra) $\vec{x}$, we need to view the vector as a column matrix. We define the matrix-vector only for the case when the number of columns in $\matrix{A}$ equals the number of rows in $\vec{x}$.

So, if $\matrix{A}$ is an $m \times n$ matrix (i.e., with $n$ columns), the product $A\vec{x}$ is defined for $n \times 1$ column vectors $\vec{x}$. If we let $A \vec{x} = \vec{b}$, then $\vec{b}$ is an $m \times 1$ column vector. 

The general formula for a matrix-vector product is 

$$\begin{align*}
  A\vec{x}=
  \left[
    \begin{array}{cccc}
      a_{11} & a_{12} & \ldots & a_{1n}\\
      a_{21} & a_{22} & \ldots & a_{2n}\\
      \vdots & \vdots & \ddots & \vdots\\
      a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{array}
  \right]
  \left[
    \begin{array}{c}
      x_1\\
      x_2\\
      \vdots\\
      x_n
    \end{array}
  \right]
  =
  \left[
    \begin{array}{c}
      a_{11}x_1+a_{12}x_2 + \cdots + a_{1n} x_n\\
      a_{21}x_1+a_{22}x_2 + \cdots + a_{2n} x_n\\
      \vdots\\
      a_{m1}x_1+a_{m2}x_2 + \cdots + a_{mn} x_n\\
    \end{array}
  \right].
\end{align*}
$$

For instance, if
$$\begin{align*}
  A = \left[
      \begin{array}{rrr}
        1 & -1 & 2\\
        0  & -3 & 1
      \end{array}
    \right]
\end{align*}$$

and $\vec{x} = (2,1,0)$, then


$$\begin{align*}
  A \vec{x} &= \left[
    \begin{array}{rrr}
      1 & -1 & 2\\
      0  & -3 & 1
    \end{array}
  \right]
  \left[
    \begin{array}{l}
      2\\1\\0
    \end{array}
  \right]\\
  &=
  \left[
    \begin{array}{r}
      2 \cdot 1 - 1\cdot 1 + 0 \cdot 2\\
      2 \cdot 0 - 1 \cdot 3 +0 \cdot 1
    \end{array}
  \right]
  \\
  &=
  \left[
    \begin{array}{r}
      1\\
      -3
    \end{array}
  \right]
\end{align*}$$

Another way of interpreting the matrix-vector product is that if $\vec{b} = \matrix{A}\vec{x}$, then $\vec{b}$ is **a linear combination of the columns of A**.

### Python Implementation

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -1, 2],
              [0, -3, 1]])
A

array([[ 1, -1,  2],
       [ 0, -3,  1]])

In [3]:
# Shape of A
A.shape

(2, 3)

In [4]:
x = np.array([2, 1, 0])
x

array([2, 1, 0])

In [5]:
# Shape of x
x.shape

(3,)

In [6]:
# Matrix-vector product
Ax = A @ x.T   # same as A.dot(x.T)

In [7]:
Ax

array([ 1, -3])

**NOTE**: ![](https://i.imgur.com/W8TXnLH.png)

(source: [What is the '@=' symbol for in Python?](https://stackoverflow.com/questions/27385633/what-is-the-symbol-for-in-python))

## Matrix-matrix product

Since we view vectors as column matrices, the matrix-vector product is *simply a special case of the matrix-matrix product*(i.e., a product of two matrices). Just like for the matrix-vector product, the product $AB$ between matrices $A$ and $B$ is defined only if the number of *columns* in $A$ equals the number of *rows* in $B$. Mathematically, we say we can multiply an $m \times n$ matrix $A$ by an $n \times p$ matrix $B$.

**NOTE:** if $p$ happened to be $1$, then $B$ would be an $n \times 1$ column vector and we'd be back to the matrix-vector product.

The product $AB$ is an $m \times p$ matrix which we will call $C$, i.e., $AB = C$. To calculate the product $B$, we view $B$ as a bunch of $n \times 1$ column vectors lined up next to each other:

$$\begin{align*}
    \left[
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1p}\\
      b_{21} & b_{22} & \ldots & b_{2p}\\
      \vdots & \vdots & \vdots & \vdots\\
      b_{n1} & b_{n2} & \ldots & b_{np}
    \end{array}
  \right]
  =
    \left[
    \left[
    \begin{array}{c}
      b_{11}\\
      b_{21}\\
      \vdots\\
      b_{n1}\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
      b_{12}\\
      b_{22}\\
      \vdots\\
      b_{n2}\\
    \end{array}
    \right]
    \cdots
    \left[
    \begin{array}{c}
      b_{1p}\\
      b_{2p}\\
      \vdots\\
      b_{np}\\
    \end{array}
    \right]
  \right]
\end{align*}$$

Then each column of $C$ is the matrix-vector product of $A$ with the respective column of $B$. In other words, the component in the $i$th row and $j$th column of $C$ is the dot product between the $i$th row of $A$ and the $j$th column of $B$.

Mathematically, we write this component of $C$ as $$c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + \cdots +
a_{in}b_{nj}$$

**Example:** 
1) Compute $BC$, where
$$\begin{align*}
  B=
  \left[
    \begin{array}{rrr}
      1 &2 &3\\
      4 &5 &6
    \end{array}
  \right]
  \qquad
  \text{and}
  \qquad
  C=
  \left[
    \begin{array}{rr}
      1 &2\\
      3 & 4\\
      5 &6
    \end{array}
  \right].
\end{align*}$$

**Solution**
$$\begin{align*}
  BC &=
  \left[
    \begin{array}{rrr}
      1 &2 &3\\
      4 &5 &6
    \end{array}
  \right]
  \left[
    \begin{array}{rr}
      1 &2\\
      3 & 4\\
      5 &6
    \end{array}
  \right]
  \\
  &=
  \left[
    \begin{array}{ccc}
      1\cdot 1 + 2\cdot 3 + 3\cdot 5 
      &&  1\cdot 2 + 2\cdot 4 + 3\cdot 6 \\
      4\cdot 1 +5\cdot 3 +6\cdot 5
      && 4\cdot 2 +5\cdot 4 +6\cdot 6
    \end{array}
  \right]
  \\
  &=
  \left[
    \begin{array}{cc}
      22 & 28\\
      49 & 64
    \end{array}
  \right]
\end{align*}$$

2) Using $B$ and $C$, calculate $CB$.

**Solution**:
$$\begin{align*}
  CB &=
  \left[
    \begin{array}{rr}
      1 &2\\
      3 & 4\\
      5 &6
    \end{array}
  \right]
 \left[
    \begin{array}{rrr}
      1 &2 &3\\
      4 &5 &6
    \end{array}
  \right]
  \\
  &=
  \left[
    \begin{array}{ccccc}
      1\cdot 1 + 2\cdot 4
      &&1\cdot 2 + 2\cdot 5
      &&1\cdot 3 + 2\cdot 6\\
      3\cdot 1 + 4\cdot 4
      &&3\cdot 2 + 4\cdot 5
      &&3\cdot 3 + 4\cdot 6\\
      5\cdot 1 + 6\cdot 4
      &&5\cdot 2 + 6\cdot 5
      &&5\cdot 3 + 6\cdot 6
    \end{array}
  \right]
  \\
  &=
  \left[
    \begin{array}{rrr}
      9 & 12 & 15\\
      19 & 26 & 33\\
      29 & 40 & 51
    \end{array}
  \right]
\end{align*}$$

### Python Implementation

In [8]:
B = np.array([[1, 2, 3], [4, 5, 6]])
C = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(B.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
print(C)
print(C.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
# Matrix - Matrix product
BC = B @ C
BC

array([[22, 28],
       [49, 64]])

In [11]:
CB = C @ B
CB

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

Clearly, one can see that the matrix multiplication is not commutative, i.e, $BC \ne CB$. In the previous example, $BC$ isn't even the same size matrix as $CB$. In some other cases, $BC$ might be defined but $CB$ won't be defined( for instance, when $B$ is a $3 \times 2$ matrix and $C$ is a $2 \times 4$ matrix).

In [12]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [13]:
C = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
C.shape

(2, 4)

In [14]:
BC = B @ C
BC

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [15]:
BC.shape

(3, 4)

In [16]:
CB = C @ B

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

## Rank of a Matrix

The **rank** of a matrix is defined as 
1. the maximum number of **linearly independent column vectors** in the matrix. or
2. the maximum number of **linearly independent row vectors** in the matrix. 

Both definitions are equivalent. 

**NOTE:** ![](https://i.imgur.com/3LyTpDG.png)
(Source: [Stat Trek](https://i.imgur.com/3LyTpDG.png))

### How to Find Matrix Rank
The following section describes the method used to find the rank of any matrix. This method assumes familiarity with [echelon matrices](http://stattrek.com/matrix-algebra/echelon-matrix.aspx) and [echelon transformations](http://stattrek.com/matrix-algebra/echelon-transform.aspx).

The maximum number of linearly independent vectors in a matrix is equal to the number of non-zero rows in its row echelon matrix. Therefore, to find the rank of a matrix, we simply transform the matrix to its row echelon form and count the number of non-zero rows.

Consider matrix $A$ and its row echelon matrix, $A_{ref}$
$$A = \begin{bmatrix}
0 & 1 & 2\\ 
1 & 2 & 1 \\ 
2 & 7 & 8
\end{bmatrix}\Rightarrow A_{ref} = \begin{bmatrix}
1 & 0 & -3\\ 
0 & 1 & 2 \\ 
0 & 0 & 0
\end{bmatrix}$$

![](https://i.imgur.com/g3KNqiX.png)

Because the row echelon form $A_{ref}$ has two non-zero rows, we know that matrix $A$ has **two independent row vectors**; and we know that **the rank of matrix A is 2**.

In [17]:
from sympy import Matrix

In [18]:
A = Matrix([[0, 1, 2], [1, 2, 1], [2, 7, 8]])
A

Matrix([
[0, 1, 2],
[1, 2, 1],
[2, 7, 8]])

In [19]:
# Row echelon form
A_ref = A.rref()
A_ref

(Matrix([
 [1, 0, -3],
 [0, 1,  2],
 [0, 0,  0]]), (0, 1))

SymPy ```rref()``` attribute returns a tuple of two elements. The first is the reduced row echelon form, and the second is a list of indices of the pivot columns.

In [20]:
# Matrix Rank
A.rank()

2

### Full Rank Matrices

When all of the **vectors** in a matrix are **linearly independent**, the matrix is said to be **full rank**. Consider the matrices A and B below.

$$A = \begin{bmatrix}
1 & 2 & 3\\ 
2 & 4 & 6
\end{bmatrix}$$

$$B = \begin{bmatrix}
1 & 0 & 2\\ 
2 & 1 & 0\\ 
3 &  2& 1
\end{bmatrix}$$

Notice that row 2 of matrix $A$ is a scalar multiple of row 1; that is, row 2 is equal to twice row 1. Therefore, rows 1 and 2 are linearly dependent. Matrix $A$ has only one linearly independent row, so its rank is 1. Hence, **matrix A is not full rank**.

Now, look at matrix $B$. All of its rows are linearly independent, so the rank of matrix $B$ is 3. **Matrix B is full rank**.

In [24]:
A = Matrix([[1, 2, 3], [2, 4, 6]])
A

Matrix([
[1, 2, 3],
[2, 4, 6]])

In [25]:
A.rank()

1

In [26]:
B = Matrix([[1, 0, 2], [2, 1, 0], [3, 2, 1]])
B

Matrix([
[1, 0, 2],
[2, 1, 0],
[3, 2, 1]])

In [27]:
B.rank()

3

## Nullspace

If A is a matrix, the **nullspace** is the set of off all vector s $\vec{x}$ such that $A\vec{x}=0$. 

It is good to think of the matrix; if tou let $f(x) = A \vec{x}$, then the nullspace is again the set of all vectors that are sent to to the zero vector by $f$. In other words, the set of vectors that **lose their identity** as $f$ is applied to them.

**NOTE:** Nullity is the complement to the rank of a matrix. They are both really important. **rank** + ** dim Null A**  = total number of columns.

### How to Find Nullspace

- **Step 1:** Transform the matrix to the reduced row echelon form
- **Step 2:** Interpret the reduced row echelon form

Find the nullspace of the matrix
$$A = \begin{bmatrix}
0 & 1 & 2\\ 
1 & 2 & 1 \\ 
2 & 7 & 8
\end{bmatrix}$$

**Step 1: Transform the matrix to the reduced row echelon form**
![](https://i.imgur.com/g3KNqiX.png)

**Step 2: Interpret the reduced row echelon form**

The reduced row echelon form of the augmented matrix is
$$A_{ref} = \begin{bmatrix}
1 & 0 & -3\\ 
0 & 1 & 2 \\ 
0 & 0 & 0
\end{bmatrix}$$

which corresponds to the system

$$\left\{\begin{matrix}
1x_1 &  &  - 3x_3 & = 0 \\ 
 & 1 x_2 & + 2x_3  & = 0 \\ 
 &  & 0 & = 0
\end{matrix}\right.$$

A leading entry on the $(i,j)$ position indicates that the $j$th unknown will be determined using the $i$th equation. 

Those columns in the coefficient part of the matrix that do not contain leading entries, correspond to unknowns that will be arbitrary. The system has **infinetly many solutions**:

$$\begin{matrix}
x_1 & = & 3x_3\\ 
x_2 & = & -2x_3\\ 
x3 & = & \text{arbitrary}
\end{matrix}$$

Therefore, the **nullspcace** has a basis formed by the set 
$$\begin{Bmatrix}
3\\ 
-2\\ 
1\end{Bmatrix}$$

- The **rank** of the matrix is 2. It equals the number of **leading entries**.
- The **nullity** of the matrix is 1. This is the dimension of the null space. It equals the number of **columns without leading entries**. 

In [21]:
# Reduced echelon form
A_ref

(Matrix([
 [1, 0, -3],
 [0, 1,  2],
 [0, 0,  0]]), (0, 1))

In [22]:
A_nullspace = A.nullspace()
A_nullspace

[Matrix([
 [ 3],
 [-2],
 [ 1]])]

## Matrix Determinant

In [43]:
%load_ext version_information
%version_information numpy, sympy

Software versions
Python 3.6.3 64bit [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
IPython 6.2.1
OS Linux 4.4.0 53 generic x86_64 with debian stretch sid
numpy 1.12.1
sympy 1.1.1
Fri Oct 13 09:58:57 2017 CDT

## References

- [1] [Numerical Linear Algebra](https://www.amazon.com/Numerical-Linear-Algebra-Lloyd-Trefethen/dp/0898713617) by Trefethen and Bau.

In [23]:
A.adjoint()

Matrix([
[0, 1, 2],
[1, 2, 7],
[2, 1, 8]])

In [40]:
init_printing()

In [32]:
from sympy import *

In [41]:
x, y, z = symbols('x y z')

In [42]:
x

In [43]:
exp(x)

In [44]:
(exp(x)/ factorial(y)) ** z